Slice and dice packages/govuk react button
FSA-Civica/govuk-react pull request #2
Opened 2021-03-09 12:47 UTC by david-kasali

**Checklist**:

* [ ] Documentation
* [ ] Tests
* [ ] Ready to be merged

2021-03-09 13:00 UTC, paul-burnett requested changes

2021-03-09 13:00 UTC, paul-burnett commented on components/button/src/index.js
> +const FOCUSABLE = {
Don't need to add this here, just update constants package in `packages/constants/src`, and publish to slice-and-dice npm.  Let me know if you need a hand with this

2021-03-09 13:01 UTC, paul-burnett commented on components/button/src/index.js
> +const FOCUSABLE = {
As per the 'radio' PR comment, should also be using updated govuk-colours package instead of hardcoding colour hex

2021-03-10 11:32 UTC, paul-burnett commented on components/button/src/index.js
> +const FOCUSABLE = {
This change no longer required now we have updated base to use the latest GDS colours?

2021-03-10 11:34 UTC, david-kasali commented on components/button/src/index.js
> +const FOCUSABLE = {
Yeah that's right

2021-03-10 11:34 UTC, closed without merging